baseURL = 'https://celinewang.fr/'
languageCode = 'en-us'
title = 'Personal Web Page'
theme = 'hugo-theme-m10c'

[pagination]
  pagerSize = 8

[params]
    author = "Céline Wang"
    avatar = "./avatar.png"
    description = "PhD student in Mathematics Applied to Ecology."
    menu_item_separator = " - "
    email = "celine.wang@univ-lille.fr"
    sidebarTitle = "Céline Wang"
    
   
    [[params.social]]
        name = "Email"
        url = "mailto:celine.wang@univ-lille.fr"
        icon = "mail"
 [params.style]
    darkestColor =  "#1a1a1a"
    darkColor    =  "#2d2d2d"
    lightColor   = "#c0c0c0"
    lightestColor= "#ffffff"
    primaryColor = "#419ab0"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "CV"
        name = "CV"
        url = "/CV/"
        weight = 2

    [[menu.main]]
        identifier = "papers"
        name = "Papers"
        url = "/papers/"
        weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'